import { Backdrop, Grid } from "@mui/material";
import Head from "next/head";
import { useEffect, useState } from "react";
import Navbar from "./Navbar";

export default function Layout({ children }) {

    return (
        <Grid container>
            <Head>
                <title>Demooncracy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid item xs={12}>
                <Navbar />
            </Grid>
            <Grid item xs={12} component={"main"}>
                {children}
            </Grid>
        </Grid>
    )
}